```{r}
library(rstatix)  # pipe-friendly statistical methods
library(ggplot2)
library(ggpubr)

rdf <- read.csv('./results/results_all_long.csv')

rdf$N_EST <- as.factor(rdf$N_EST)
rdf$Index <- as.factor(rdf$Index)
rdf$FI <- as.factor(rdf$FI)
rdf$MR <- as.factor(rdf$MR)

```
```{r fig.width=4}

MR = unique(rdf$MR)
pd = position_dodge(0.6)

AUROC <- c(0.6619815875877165, 0.8290163353003178, 0.9078733931801096)
AUPRC <- c(0.10999212039806713, 0.4261383315393321, 0.6587304621389592)
MEAN_AUPRC <- c(0.19955715263807533, 0.5260921589703365, 0.7257882565622619)
MEAN_AUROC <- c(0.6725450267402954, 0.8441343415588369, 0.916339278444858)
MEAN_AUROC_GENIE <- c(0.661429878034267, 0.8464084933954908, 0.8367971767578932)


for (i in seq_along(MR)) {
  mr <- MR[i]
  baseline_value <- AUPRC[i]
  p <- rdf %>%
    filter(MR == mr) %>%
     filter(!is.na(AUPRC)) %>%
    ggplot(aes(x=Index, y=AUPRC, group = N_EST, colour = FI)) + 
    geom_point(aes(shape = N_EST), position = pd, size = 3) +
    geom_hline(yintercept = baseline_value, linetype = "dashed", color = "black", alpha = 0.5) + 
    scale_shape_manual(values=c(3,4,8))+
    theme_pubr() + 
    scale_color_brewer(palette = 'Set1') +
    facet_wrap(MR~., ncol = 1, scales = "free_y") +
    theme(legend.position = "right",
      axis.text.x = element_text(angle = 45, hjust = 1),
    )+
    xlab(NULL) + ylab('AUPRC')
    
  plot(p)
  filename <- paste0("results/", mr , "_AUPRC" , ".png")
  ggsave(filename, plot = p)
}

for (i in seq_along(MR)) {
  mr <- MR[i]
  baseline_value <- AUROC[i]
  p <- rdf %>%
    filter(MR == mr) %>%
     filter(!is.na(AUROC)) %>%
    ggplot(aes(x=Index, y=AUROC, group = N_EST, colour = FI)) + 
    geom_point(aes(shape = N_EST), position = pd, size = 3) +
    geom_hline(yintercept = baseline_value, linetype = "dashed", color = "black", alpha = 0.5) + 
    scale_shape_manual(values=c(3,4,8))+
    theme_pubr() + 
    scale_color_brewer(palette = 'Set1') +
    facet_wrap(MR~., ncol = 1, scales = "free_y") +
    theme(legend.position = "right",
      axis.text.x = element_text(angle = 45, hjust = 1),
    )+
    xlab(NULL) + ylab('AUROC')
    
  plot(p)
  filename <- paste0("results/", mr , "_AUROC" , ".png")
  ggsave(filename, plot = p)
}

for (i in seq_along(MR)) {
  mr <- MR[i]
  baseline_value <- MEAN_AUPRC[i]
  p <- rdf %>%
    filter(MR == mr) %>%
     filter(!is.na(MEAN_AUPRC)) %>%
    ggplot(aes(x=Index, y=MEAN_AUPRC, group = N_EST, colour = FI)) + 
    geom_errorbar(aes(ymin=MEAN_AUPRC-STD_AUPRC, ymax=MEAN_AUPRC+STD_AUPRC), 
                  width=0.4, size = 0.5, position=pd, alpha = 1) +
    geom_point(aes(shape = N_EST), position = pd, size = 3) +
    geom_hline(yintercept = baseline_value, linetype = "dashed", color = "black", alpha = 0.5) +
    scale_shape_manual(values=c(3,4,8))+
    theme_pubr() + 
    scale_color_brewer(palette = 'Set1') +
    facet_wrap(MR~., ncol = 1, scales = "free_y") +
    theme(legend.position = "right",
      axis.text.x = element_text(angle = 45, hjust = 1),
    )+
    xlab(NULL) + ylab('AUPRC')
    
  plot(p)
  filename <- paste0("results/", mr , "_MEAN_AUPRC" , ".png")
  ggsave(filename, plot = p)
}

for (i in seq_along(MR)) {
  mr <- MR[i]
  baseline_value <- MEAN_AUROC[i]
  genie_value <- MEAN_AUROC_GENIE[i]
  p <- rdf %>%
    filter(MR == mr) %>%
     filter(!is.na(MEAN_AUROC)) %>%
    ggplot(aes(x=Index, y=MEAN_AUROC, group = N_EST, colour = FI)) + 
    geom_errorbar(aes(ymin=MEAN_AUROC-STD_AUROC, ymax=MEAN_AUROC+STD_AUROC), 
                  width=0.4, size = 0.5, position=pd, alpha = 1) +
    geom_point(aes(shape = N_EST), position = pd, size = 3) +
    geom_hline(yintercept = baseline_value, linetype = "dashed", color = "black", alpha = 0.5) + 
    geom_hline(yintercept = genie_value, linetype = "dashed", color = "green", alpha = 0.5) + 
    scale_shape_manual(values=c(3,4,8))+
    theme_pubr() + 
    scale_color_brewer(palette = 'Set1') +
    facet_wrap(MR~., ncol = 1, scales = "free_y") +
    theme(legend.position = "right",
      axis.text.x = element_text(angle = 45, hjust = 1),
    )+
    xlab(NULL) + ylab('AUROC')
    
  plot(p)
  filename <- paste0("results/", mr , "_MEAN_AUROC" , ".png")
  ggsave(filename, plot = p)
}
```



